server {
    listen 9443 ssl;
    server_name portal.cargo.skytrust.local localhost;

    ssl_certificate     /etc/nginx/cargo-pki/serveur-cargo.pem;
    ssl_certificate_key /etc/nginx/cargo-pki/portal-server.key;
    ssl_client_certificate /etc/nginx/cargo-pki/cargo-chain.pem;
    ssl_verify_client on;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        return 200 'SkyTrust Cargo Portal - Acces autorise pour $ssl_client_s_dn\n';
        add_header Content-Type text/plain;
    }
}
